import type { ArtifactDefinition } from "../../core/content/artifact-content";

export const artifactDefinitions: readonly ArtifactDefinition[] = [
  {
    id: "attack_up",
    name: "Sharpened Edge",
    descriptionTemplate: "+%d normal attack damage",
    category: "minor",
    maxStacks: 3,
    exclusivityGroup: "",
    isCurse: false,
    minWave: 1,
    magnitude: 10,
    requiredMobility: null,
    effects: [{ kind: "channel", channel: "normal-attack-damage", amount: 10 }],
    presentation: { id: "artifact.attack_up" },
  },
  {
    id: "speed_up",
    name: "Fleet Step",
    descriptionTemplate: "+%d Speed",
    category: "minor",
    maxStacks: 5,
    exclusivityGroup: "",
    isCurse: false,
    minWave: 1,
    magnitude: 1,
    requiredMobility: null,
    effects: [{ kind: "channel", channel: "speed", amount: 1 }],
    presentation: { id: "artifact.speed_up" },
  },
  {
    id: "dash_attack_up",
    name: "Impact Dash",
    descriptionTemplate: "+%d dash attack damage",
    category: "minor",
    maxStacks: 3,
    exclusivityGroup: "",
    isCurse: false,
    minWave: 1,
    magnitude: 20,
    requiredMobility: null,
    effects: [{ kind: "channel", channel: "mobility-attack-damage", amount: 20 }],
    presentation: { id: "artifact.dash_attack_up" },
  },
  {
    id: "mobility_cooldown_down",
    name: "Light Footwork",
    descriptionTemplate: "-%d mobility cooldown (ticks)",
    category: "minor",
    maxStacks: 3,
    exclusivityGroup: "",
    isCurse: false,
    minWave: 1,
    magnitude: 1,
    requiredMobility: null,
    effects: [{ kind: "channel", channel: "mobility-cooldown", amount: 1 }],
    presentation: { id: "artifact.mobility_cooldown_down" },
  },
  {
    id: "mobility_range_up",
    name: "Extended Mobility",
    descriptionTemplate: "+%d Mobility Range",
    category: "minor",
    maxStacks: 3,
    exclusivityGroup: "",
    isCurse: false,
    minWave: 1,
    magnitude: 1,
    requiredMobility: null,
    effects: [{ kind: "channel", channel: "mobility-range", amount: 1 }],
    presentation: { id: "artifact.mobility_range_up" },
  },
  {
    id: "max_health_up",
    name: "Vital Spark",
    descriptionTemplate: "+%d max health",
    category: "minor",
    maxStacks: 2,
    exclusivityGroup: "",
    isCurse: false,
    minWave: 1,
    magnitude: 20,
    requiredMobility: null,
    effects: [{ kind: "channel", channel: "max-health", amount: 20 }],
    presentation: { id: "artifact.max_health_up" },
  },
  {
    id: "guard_shredder",
    name: "Guard Shredder",
    descriptionTemplate: "Back-angle dash hits break guard instantly (%d)",
    category: "major",
    maxStacks: 1,
    exclusivityGroup: "",
    isCurse: false,
    minWave: 2,
    magnitude: 1,
    requiredMobility: "dash",
    effects: [{ kind: "trigger", trigger: "guard-shredder" }],
    presentation: { id: "artifact.guard_shredder" },
  },
  {
    id: "execution",
    name: "Execution",
    descriptionTemplate: "Dash hits on staggered targets kill instantly (%d)",
    category: "major",
    maxStacks: 1,
    exclusivityGroup: "",
    isCurse: false,
    minWave: 2,
    magnitude: 1,
    requiredMobility: "dash",
    effects: [{ kind: "trigger", trigger: "execution" }],
    presentation: { id: "artifact.execution" },
  },
  {
    id: "chain_dash",
    name: "Chain Dash",
    descriptionTemplate: "Back, guard-break, stagger, or kill Dash hits clear Dash cooldown and ready your next move or attack (%d)",
    category: "major",
    maxStacks: 1,
    exclusivityGroup: "",
    isCurse: false,
    minWave: 2,
    magnitude: 1,
    requiredMobility: "dash",
    effects: [{ kind: "trigger", trigger: "chain-dash" }],
    presentation: { id: "artifact.chain_dash" },
  },
];
