import type {
  AttackDefinition,
  EnemyDefinition,
  GuardDefinition,
} from "../../core/content/actor-schema";

export const guardDefinitions: readonly GuardDefinition[] = [
  {
    id: "small",
    name: "Small",
    base: 32,
    lethalTierGain: 8,
    stagger: 3,
    protection: 5,
    protectionMultiplier: 0.5,
  },
  {
    id: "heavy",
    name: "Heavy",
    base: 64,
    lethalTierGain: 16,
    stagger: 3,
    protection: 5,
    protectionMultiplier: 0.5,
  },
];

export const attackDefinitions: readonly AttackDefinition[] = [
  {
    id: "thrust",
    name: "Thrust",
    kind: "tile",
    damage: 10,
    warningTicks: 2,
    recoveryTicks: 2,
    shape: {
      shape: "custom-offsets",
      offsets: [
        { x: 1, y: 0 },
        { x: 2, y: 0 },
        { x: 3, y: 0 },
      ],
    },
  },
  {
    id: "slash",
    name: "Slash",
    kind: "tile",
    damage: 10,
    warningTicks: 2,
    recoveryTicks: 2,
    shape: {
      shape: "custom-offsets",
      offsets: [
        { x: 1, y: -1 },
        { x: 1, y: 0 },
        { x: 1, y: 1 },
      ],
    },
  },
  {
    id: "ranged_cross",
    name: "Ranged Cross",
    kind: "tile",
    damage: 10,
    warningTicks: 2,
    recoveryTicks: 1,
    shape: {
      shape: "custom-offsets",
      offsets: [
        { x: 0, y: 0 },
        { x: 1, y: 0 },
        { x: -1, y: 0 },
        { x: 0, y: 1 },
        { x: 0, y: -1 },
      ],
    },
  },
  {
    id: "charge",
    name: "Charge",
    kind: "charge",
    damage: 8,
    warningTicks: 2,
    recoveryTicks: 2,
    shape: { shape: "line", length: 5 },
  },
  {
    id: "bomb_area",
    name: "Bomb Area",
    kind: "area",
    damage: 50,
    warningTicks: 3,
    recoveryTicks: 1,
    shape: { shape: "manhattan", radius: 3 },
  },
];

export const enemyDefinitions: readonly EnemyDefinition[] = [
  {
    id: "thrust_enemy",
    name: "Thrust Enemy",
    role: "thrust",
    speed: 75,
    hp: 100,
    defense: 0,
    guardId: "small",
    attackIds: ["thrust"],
    roleTuning: null,
    presentation: { id: "enemy.thrust" },
    audio: { id: "enemy.guarded" },
  },
  {
    id: "slash_enemy",
    name: "Slash Enemy",
    role: "slash",
    speed: 75,
    hp: 100,
    defense: 0,
    guardId: "small",
    attackIds: ["slash"],
    roleTuning: null,
    presentation: { id: "enemy.slash" },
    audio: { id: "enemy.guarded" },
  },
  {
    id: "ranged_enemy",
    name: "Ranged Enemy",
    role: "ranged",
    speed: 75,
    hp: 100,
    defense: 0,
    guardId: "small",
    attackIds: ["ranged_cross"],
    roleTuning: {
      type: "ranged",
      minDistance: 3,
      maxDistance: 5,
    },
    presentation: { id: "enemy.ranged" },
    audio: { id: "enemy.guarded" },
  },
  {
    id: "charge_enemy",
    name: "Charge Enemy",
    role: "charge",
    speed: 100,
    hp: 150,
    defense: 0,
    guardId: "heavy",
    attackIds: ["charge"],
    roleTuning: null,
    presentation: { id: "enemy.charge" },
    audio: { id: "enemy.guarded" },
  },
  {
    id: "bomb_enemy",
    name: "Bomb Enemy",
    role: "bomb",
    speed: 75,
    hp: 50,
    defense: 0,
    guardId: null,
    attackIds: ["bomb_area"],
    roleTuning: { type: "bomb", commitment: "adjacent" },
    presentation: { id: "enemy.bomb" },
    audio: { id: "enemy.guardless" },
  },
];
